// Modo ESM: Vercel y "type":"module" requieren import/export
import Replicate from "replicate";
import dotenv from "dotenv";

// Cargar variables de entorno desde .env.local en desarrollo
dotenv.config({ path: ".env.local" });

// Inicializamos Replicate con nuestro API Token
const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

// Handler de la función serverless
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ message: 'Method Not Allowed' });
    return;
  }

  try {
    // Validar credenciales antes de llamar a Replicate
    if (!process.env.REPLICATE_API_TOKEN) {
      res.status(401).json({ message: 'Missing REPLICATE_API_TOKEN on server' });
      return;
    }

    const body = typeof req.body === 'string'
      ? JSON.parse(req.body)
      : (req.body || {});
    const { prompt } = body;

    if (!prompt) {
      res.status(400).json({ message: 'Prompt is required' });
      return;
    }

    // --- INICIO DEL CÓDIGO NUEVO ---
    // 3. Llamar a la API de Replicate
    // (Usamos un modelo público y estable: Stable Diffusion)
    // Usar versión específica válida de Stable Diffusion
    const output = await replicate.run(
      "stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",
      {
        input: {
          prompt: `${prompt}, pixel art, 8-bit sprite`
        }
      }
    );
    // --- FIN DEL CÓDIGO NUEVO ---

    // 4. Enviar la URL de la imagen de vuelta al frontend
    if (output && output.length > 0) {
      res.status(200).json({ imageUrl: output[0] });
    } else {
      throw new Error('No image generated by Replicate');
    }

  } catch (error) {
    // Intentar mapear código de estado desde el mensaje
    const m = String(error.message || '').match(/status\s(\d+)/);
    const status = m ? Number(m[1]) : 500;
    // Intentar extraer JSON embebido en el mensaje
    let serverDetail;
    try {
      const jsonMatch = String(error.message).match(/\{[\s\S]*\}$/);
      serverDetail = jsonMatch ? JSON.parse(jsonMatch[0]) : undefined;
    } catch (_) {}

    console.error("Error en la API de Replicate:", error.message);
    res.status(status).json({
      message: serverDetail?.detail || error.message || 'Failed to generate image',
      title: serverDetail?.title,
      error: error.message,
      status
    });
  }
}