// ESM module: using import/export because the project is "type":"module"
import Replicate from "replicate";
import dotenv from "dotenv";

// Load environment variables from .env.local during local development
dotenv.config({ path: ".env.local" });

// Initialize Replicate client using our API token
const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

// Serverless API handler
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ message: 'Method Not Allowed' });
    return;
  }

  try {
    // Guard: ensure the API token is present before calling Replicate
    if (!process.env.REPLICATE_API_TOKEN) {
      res.status(401).json({ message: 'Missing REPLICATE_API_TOKEN on server' });
      return;
    }

    const body = typeof req.body === 'string'
      ? JSON.parse(req.body)
      : (req.body || {});
    const { prompt } = body;

    if (!prompt) {
      res.status(400).json({ message: 'Prompt is required' });
      return;
    }

    // Call Replicate to generate an image (with a pixel‑art flavor)
    // Use a specific Stable Diffusion version known to be accessible
    const output = await replicate.run(
      "stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",
      {
        input: {
          prompt: `${prompt}, pixel art, 8-bit sprite`
        }
      }
    );

    // Return the first image URL back to the client
    if (output && output.length > 0) {
      res.status(200).json({ imageUrl: output[0] });
    } else {
      throw new Error('No image generated by Replicate');
    }

  } catch (error) {
    // Try to infer the HTTP status code from the error text
    const m = String(error.message || '').match(/status\s(\d+)/);
    const status = m ? Number(m[1]) : 500;
    // Try to parse an embedded JSON payload from the error message
    let serverDetail;
    try {
      const jsonMatch = String(error.message).match(/\{[\s\S]*\}$/);
      serverDetail = jsonMatch ? JSON.parse(jsonMatch[0]) : undefined;
    } catch (_) {}

    console.error("Replicate API error:", error.message);
    res.status(status).json({
      message: serverDetail?.detail || error.message || 'Failed to generate image',
      title: serverDetail?.title,
      error: error.message,
      status
    });
  }
}